/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "DoubleGaussian.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooGaussian.h"

ClassImp(DoubleGaussian) 

DoubleGaussian::DoubleGaussian(const char *name, const char *title, 
                       RooAbsReal& _x,
                       RooAbsReal& _mean,
                       RooAbsReal& _sig1,
                       RooAbsReal& _sig2) :
  RooAbsPdf(name,title), 
  x("x","x",this,_x),
  mean("mean","mean",this,_mean),
  sig1("sig1","sig1",this,_sig1),
  sig2("sig2","sig2",this,_sig2)
{ 
} 


DoubleGaussian::DoubleGaussian(const DoubleGaussian& other, const char* name) :  
  RooAbsPdf(other,name), 
  x("x",this,other.x),
  mean("mean",this,other.mean),
  sig1("sig1",this,other.sig1),
  sig2("sig2",this,other.sig2)
{ 
} 



Double_t DoubleGaussian::evaluate() const 
{ 
  double result = -1;
  double A = TMath::Power(2/TMath::Pi(), 0.5) / (sig1 + sig2); 
  if ( x < mean)
    result = TMath::Exp( (x-mean) * (x-mean) / 2 / sig1 / sig1);
  else
    result = TMath::Exp( (x-mean) * (x-mean) / 2 / sig2 / sig2);
  return A*result ;
} 



