/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "CombineLimits/Limits/interface/DoubleCrystalBall.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(DoubleCrystalBall) 

 DoubleCrystalBall::DoubleCrystalBall(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _mean,
                        RooAbsReal& _sig,
                        RooAbsReal& _a1,
                        RooAbsReal& _n1,
                        RooAbsReal& _a2,
                        RooAbsReal& _n2) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mean("mean","mean",this,_mean),
   sig("sig","sig",this,_sig),
   a1("a1","a1",this,_a1),
   n1("n1","n1",this,_n1),
   a2("a2","a2",this,_a2),
   n2("n2","n2",this,_n2)
 { 
 } 


 DoubleCrystalBall::DoubleCrystalBall(const DoubleCrystalBall& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mean("mean",this,other.mean),
   sig("sig",this,other.sig),
   a1("a1",this,other.a1),
   n1("n1",this,other.n1),
   a2("a2",this,other.a2),
   n2("n2",this,other.n2)
 { 
 } 



Double_t DoubleCrystalBall::evaluate() const 
{ 
	double u   = (x-mean)/sig;
	double A1  = TMath::Power(n1/TMath::Abs(a1),n1)*TMath::Exp(-a1*a1/2);
	double A2  = TMath::Power(n2/TMath::Abs(a2),n2)*TMath::Exp(-a2*a2/2);
	double B1  = n1/TMath::Abs(a1) - TMath::Abs(a1);
	double B2  = n2/TMath::Abs(a2) - TMath::Abs(a2);

	double result(1);
	if      (u<-a1) result *= A1*TMath::Power(B1-u,-n1);
	else if (u<a2)  result *= TMath::Exp(-u*u/2);
	else            result *= A2*TMath::Power(B2+u,-n2);
 	return result;
} 



