/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MY_ERF
#define MY_ERF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooErf : public RooAbsPdf {
public:
  RooErf() {} ; 
  RooErf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _shift,
	      RooAbsReal& _scale);
  RooErf(const RooErf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooErf(*this,newname); }
  inline virtual ~RooErf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

  RooRealProxy x ;
  RooRealProxy shift ;
  RooRealProxy scale ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooErf,1) // Your description goes here...
};
 
#endif

